### PR TITLE
Remove 'using namespace std' from all headers

### PR DESCRIPTION
**Pull request by emersonknapp**
Closes https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/538

Remove `using namespace std` from all headers in the project, so as to not irreversibly modify the global namespace for users of this library.

### CODE REVIEW

**Comment by emersonknapp** [comment]
@mushmal requesting review

**Comment by emersonknapp** [comment]
Ah - I didn't have the gstreamer plugin enabled in my local build

**Comment by MushMal** [comment]
> Ah - I didn't have the gstreamer plugin enabled in my local build

Thanks for taking care of it. The changes look good. Let's wait for the clean build. I am pretty sure the tests will still fail due to the need to have credentials to run against the backend. We will address that by re-submitting the PR

**Comment by MushMal** [comment]
Few more compile errors.

**Comment by emersonknapp** [comment]
Ok looks like tests also don't build by default - noting that I am now using configuration

```
cmake .. -DBUILD_GSTREAMER_PLUGIN=ON -DBUILD_JNI=OFF -DBUILD_DEPENDENCIES=ON -DBUILD_TEST=ON
```

**Comment by emersonknapp** [comment]
@MushMal from what I can tell it is now test failures due to credentials, is that correct?

**Comment by MushMal** [comment]
> @MushMal from what I can tell it is now test failures due to credentials, is that correct?

Oh yes, these are auth failures. Let us take care of it and push the commit

**Comment by emersonknapp** [comment]
Resolved by https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/pull/544

**Pull request closed without merging**
