### PR TITLE
change the unit of storage-size of gstreamer from KB to MB in README

### PR DESCRIPTION
**Pull request by toshitanian**
*Issue #, if available:*

https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/582

*Description of changes:*

Change the unit of storage-size of gstreamer from KB to MB in README

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by toshitanian** [comment]
@MushMal changed the README

**Review by MushMal — APPROVED** [review]
Thanks again!

**Comment by MushMal** [comment]
Seems that the travis CI is failing due to credentials. I could resubmit the PR but instead, I will just include the changes in the set of changes I am making to the documentation anyway. I am going to close this PR and take the changes in.

**Comment by toshitanian** [comment]
ok. thanks

**Pull request merged**
