### PR TITLE
Update version of openssl that's built

### PR DESCRIPTION
**Pull request by daveisfera**
*Issue #, if available:*
N/A

*Description of changes:*
Update to the latest version of openssl for good measure

### CODE REVIEW

**Comment by daveisfera** [comment]
There are 7 CVEs and a few other security fixes, so just seems like a good idea and the right thing to do

**Comment by hassanctech** [comment]
We can consider this however we've found even around our selected version of openssl there were adjacent ones that for example didn't build on ARM platform, we will look into this and see if there are any issues.  We must support mips as well so will need to test that one also.  If you have tested our SDK with this version on a mips/arm platform and had no issues that datapoint would be helpful feel free to share!

**Comment by daveisfera** [comment]
We're currently only building and running on x86

**Comment by disa6302** [comment]
Updated to 1.1.1t here: https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/pull/950

**Pull request closed without merging**
